version: "3.9"

services:
  client:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - django_server
      - go_server

  django_server:
    build: ./django
    deploy:
      replicas: ${DJANGO_REPLICAS}
      resources:
        limits:
          cpus: '0.50'
          memory: 50M

  go_server:
    build: ./go
    deploy:
      replicas: ${GO_REPLICAS}
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
